ci: Update GHA workflows to remove depreciated actions

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -17,9 +17,9 @@ jobs:
         lib-name: [timeline-state-resolver, timeline-state-resolver-types]
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
       - name: Prepare Environment
@@ -44,11 +44,11 @@ jobs:
       - test
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
         with:
           fetch-depth: 0
       - name: Use Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version-file: '.node-version'
       - name: Check release is desired
@@ -58,16 +58,29 @@ jobs:
             echo "No Token"
           elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
             echo "Publish nightly"
-            echo ::set-output name=publish::"nightly"
+            echo "publish=nightly" >> $GITHUB_OUTPUT
           else
             echo "Publish experimental"
-            echo ::set-output name=publish::"experimental"
+            echo "publish=experimental" >> $GITHUB_OUTPUT
           fi
+
       - name: Get the Prerelease tag
         id: prerelease-tag
-        uses: yuya-takeyama/docker-tag-from-github-ref-action@2b0614b1338c8f19dd9d3ea433ca9bc0cc7057ba
-        with:
-          remove-version-tag-prefix: false
+        run: |
+          echo "Git ref is: ${{ github.ref }}"
+          if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]
+          then
+            echo "tag=latest" >> $GITHUB_OUTPUT
+            echo "Tag is: latest"
+          elif [[ "${{ github.ref }}" =~ refs\/tags\/(v.+) || "${{ github.ref }}" =~ refs\/pull\/([0-9]+)\/merge || "${{ github.ref }}" =~ refs\/heads\/(.+) || "${{ github.ref }}" =~ refs\/tags\/(.+) ]]
+          then
+            echo "tag=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+            echo "Tag is: ${BASH_REMATCH[1]}"
+          else
+            echo "Could not find git tag"
+            exit 1
+          fi
+          echo "Git ref is: ${{ github.ref }}"
       - name: Prepare Environment
         if: ${{ steps.do-publish.outputs.publish }}
         run: |
